[package]
name = "rust_webdev"
version = "0.0.1"

[dependencies]
axum = "0.6.20"
hyper = "0.14.27"
tokio = { version = "1.33.0", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.4", features = ["full"] }
